/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as MapRouteImport } from './routes/map'
import { Route as ForbiddenRouteImport } from './routes/forbidden'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MythologyIndexRouteImport } from './routes/mythology.index'
import { Route as BestiaryIndexRouteImport } from './routes/bestiary.index'
import { Route as MythologySlugRouteImport } from './routes/mythology.$slug'
import { Route as CategoriesSlugRouteImport } from './routes/categories.$slug'
import { Route as BestiaryVanaraRouteImport } from './routes/bestiary.vanara'
import { Route as BestiaryValiRouteImport } from './routes/bestiary.vali'
import { Route as BestiaryTiamatRouteImport } from './routes/bestiary.tiamat'
import { Route as BestiaryTenguRouteImport } from './routes/bestiary.tengu'
import { Route as BestiarySphinxRouteImport } from './routes/bestiary.sphinx'
import { Route as BestiarySleipnirRouteImport } from './routes/bestiary.sleipnir'
import { Route as BestiarySharabhaRouteImport } from './routes/bestiary.sharabha'
import { Route as BestiarySelkieRouteImport } from './routes/bestiary.selkie'
import { Route as BestiaryRyuRouteImport } from './routes/bestiary.ryu'
import { Route as BestiaryQilinRouteImport } from './routes/bestiary.qilin'
import { Route as BestiaryPixiuRouteImport } from './routes/bestiary.pixiu'
import { Route as BestiaryPegasusRouteImport } from './routes/bestiary.pegasus'
import { Route as BestiaryOuroborosRouteImport } from './routes/bestiary.ouroboros'
import { Route as BestiaryOrochiRouteImport } from './routes/bestiary.orochi'
import { Route as BestiaryNidhoggRouteImport } from './routes/bestiary.nidhogg'
import { Route as BestiaryNagaRouteImport } from './routes/bestiary.naga'
import { Route as BestiaryMushussuRouteImport } from './routes/bestiary.mushussu'
import { Route as BestiaryMinotaurRouteImport } from './routes/bestiary.minotaur'
import { Route as BestiaryMakaraRouteImport } from './routes/bestiary.makara'
import { Route as BestiaryLongRouteImport } from './routes/bestiary.long'
import { Route as BestiaryLeviathanRouteImport } from './routes/bestiary.leviathan'
import { Route as BestiaryLamassuRouteImport } from './routes/bestiary.lamassu'
import { Route as BestiaryKitsuneRouteImport } from './routes/bestiary.kitsune'
import { Route as BestiaryKinnaraRouteImport } from './routes/bestiary.kinnara'
import { Route as BestiaryKhepriRouteImport } from './routes/bestiary.khepri'
import { Route as BestiaryKappaRouteImport } from './routes/bestiary.kappa'
import { Route as BestiaryKamadhenuRouteImport } from './routes/bestiary.kamadhenu'
import { Route as BestiaryJormungandrRouteImport } from './routes/bestiary.jormungandr'
import { Route as BestiaryHydraRouteImport } from './routes/bestiary.hydra'
import { Route as BestiaryHuginnMuninnRouteImport } from './routes/bestiary.huginn-muninn'
import { Route as BestiaryGarudaRouteImport } from './routes/bestiary.garuda'
import { Route as BestiaryGandharvaRouteImport } from './routes/bestiary.gandharva'
import { Route as BestiaryGalluRouteImport } from './routes/bestiary.gallu'
import { Route as BestiaryFenrirRouteImport } from './routes/bestiary.fenrir'
import { Route as BestiaryFenghuangRouteImport } from './routes/bestiary.fenghuang'
import { Route as BestiaryEachUisgeRouteImport } from './routes/bestiary.each-uisge'
import { Route as BestiaryDagdaStagRouteImport } from './routes/bestiary.dagda-stag'
import { Route as BestiaryCuSithRouteImport } from './routes/bestiary.cu-sith'
import { Route as BestiaryChimeraRouteImport } from './routes/bestiary.chimera'
import { Route as BestiaryCerberusRouteImport } from './routes/bestiary.cerberus'
import { Route as BestiaryBennuRouteImport } from './routes/bestiary.bennu'
import { Route as BestiaryBehemothRouteImport } from './routes/bestiary.behemoth'
import { Route as BestiaryBansheeRouteImport } from './routes/bestiary.banshee'
import { Route as BestiaryBaiZeRouteImport } from './routes/bestiary.bai-ze'
import { Route as BestiaryApepRouteImport } from './routes/bestiary.apep'
import { Route as BestiaryAnzuRouteImport } from './routes/bestiary.anzu'
import { Route as BestiaryAmmitRouteImport } from './routes/bestiary.ammit'
import { Route as BestiaryAiravataRouteImport } from './routes/bestiary.airavata'
import { Route as BestiaryIdRouteImport } from './routes/bestiary.$id'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const MapRoute = MapRouteImport.update({
  id: '/map',
  path: '/map',
  getParentRoute: () => rootRouteImport,
} as any)
const ForbiddenRoute = ForbiddenRouteImport.update({
  id: '/forbidden',
  path: '/forbidden',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MythologyIndexRoute = MythologyIndexRouteImport.update({
  id: '/mythology/',
  path: '/mythology/',
  getParentRoute: () => rootRouteImport,
} as any)
const BestiaryIndexRoute = BestiaryIndexRouteImport.update({
  id: '/bestiary/',
  path: '/bestiary/',
  getParentRoute: () => rootRouteImport,
} as any)
const MythologySlugRoute = MythologySlugRouteImport.update({
  id: '/mythology/$slug',
  path: '/mythology/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoriesSlugRoute = CategoriesSlugRouteImport.update({
  id: '/categories/$slug',
  path: '/categories/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const BestiaryVanaraRoute = BestiaryVanaraRouteImport.update({
  id: '/bestiary/vanara',
  path: '/bestiary/vanara',
  getParentRoute: () => rootRouteImport,
} as any)
const BestiaryValiRoute = BestiaryValiRouteImport.update({
  id: '/bestiary/vali',
  path: '/bestiary/vali',
  getParentRoute: () => rootRouteImport,
} as any)
const BestiaryTiamatRoute = BestiaryTiamatRouteImport.update({
  id: '/bestiary/tiamat',
  path: '/bestiary/tiamat',
  getParentRoute: () => rootRouteImport,
} as any)
const BestiaryTenguRoute = BestiaryTenguRouteImport.update({
  id: '/bestiary/tengu',
  path: '/bestiary/tengu',
  getParentRoute: () => rootRouteImport,
} as any)
const BestiarySphinxRoute = BestiarySphinxRouteImport.update({
  id: '/bestiary/sphinx',
  path: '/bestiary/sphinx',
  getParentRoute: () => rootRouteImport,
} as any)
const BestiarySleipnirRoute = BestiarySleipnirRouteImport.update({
  id: '/bestiary/sleipnir',
  path: '/bestiary/sleipnir',
  getParentRoute: () => rootRouteImport,
} as any)
const BestiarySharabhaRoute = BestiarySharabhaRouteImport.update({
  id: '/bestiary/sharabha',
  path: '/bestiary/sharabha',
  getParentRoute: () => rootRouteImport,
} as any)
const BestiarySelkieRoute = BestiarySelkieRouteImport.update({
  id: '/bestiary/selkie',
  path: '/bestiary/selkie',
  getParentRoute: () => rootRouteImport,
} as any)
const BestiaryRyuRoute = BestiaryRyuRouteImport.update({
  id: '/bestiary/ryu',
  path: '/bestiary/ryu',
  getParentRoute: () => rootRouteImport,
} as any)
const BestiaryQilinRoute = BestiaryQilinRouteImport.update({
  id: '/bestiary/qilin',
  path: '/bestiary/qilin',
  getParentRoute: () => rootRouteImport,
} as any)
const BestiaryPixiuRoute = BestiaryPixiuRouteImport.update({
  id: '/bestiary/pixiu',
  path: '/bestiary/pixiu',
  getParentRoute: () => rootRouteImport,
} as any)
const BestiaryPegasusRoute = BestiaryPegasusRouteImport.update({
  id: '/bestiary/pegasus',
  path: '/bestiary/pegasus',
  getParentRoute: () => rootRouteImport,
} as any)
const BestiaryOuroborosRoute = BestiaryOuroborosRouteImport.update({
  id: '/bestiary/ouroboros',
  path: '/bestiary/ouroboros',
  getParentRoute: () => rootRouteImport,
} as any)
const BestiaryOrochiRoute = BestiaryOrochiRouteImport.update({
  id: '/bestiary/orochi',
  path: '/bestiary/orochi',
  getParentRoute: () => rootRouteImport,
} as any)
const BestiaryNidhoggRoute = BestiaryNidhoggRouteImport.update({
  id: '/bestiary/nidhogg',
  path: '/bestiary/nidhogg',
  getParentRoute: () => rootRouteImport,
} as any)
const BestiaryNagaRoute = BestiaryNagaRouteImport.update({
  id: '/bestiary/naga',
  path: '/bestiary/naga',
  getParentRoute: () => rootRouteImport,
} as any)
const BestiaryMushussuRoute = BestiaryMushussuRouteImport.update({
  id: '/bestiary/mushussu',
  path: '/bestiary/mushussu',
  getParentRoute: () => rootRouteImport,
} as any)
const BestiaryMinotaurRoute = BestiaryMinotaurRouteImport.update({
  id: '/bestiary/minotaur',
  path: '/bestiary/minotaur',
  getParentRoute: () => rootRouteImport,
} as any)
const BestiaryMakaraRoute = BestiaryMakaraRouteImport.update({
  id: '/bestiary/makara',
  path: '/bestiary/makara',
  getParentRoute: () => rootRouteImport,
} as any)
const BestiaryLongRoute = BestiaryLongRouteImport.update({
  id: '/bestiary/long',
  path: '/bestiary/long',
  getParentRoute: () => rootRouteImport,
} as any)
const BestiaryLeviathanRoute = BestiaryLeviathanRouteImport.update({
  id: '/bestiary/leviathan',
  path: '/bestiary/leviathan',
  getParentRoute: () => rootRouteImport,
} as any)
const BestiaryLamassuRoute = BestiaryLamassuRouteImport.update({
  id: '/bestiary/lamassu',
  path: '/bestiary/lamassu',
  getParentRoute: () => rootRouteImport,
} as any)
const BestiaryKitsuneRoute = BestiaryKitsuneRouteImport.update({
  id: '/bestiary/kitsune',
  path: '/bestiary/kitsune',
  getParentRoute: () => rootRouteImport,
} as any)
const BestiaryKinnaraRoute = BestiaryKinnaraRouteImport.update({
  id: '/bestiary/kinnara',
  path: '/bestiary/kinnara',
  getParentRoute: () => rootRouteImport,
} as any)
const BestiaryKhepriRoute = BestiaryKhepriRouteImport.update({
  id: '/bestiary/khepri',
  path: '/bestiary/khepri',
  getParentRoute: () => rootRouteImport,
} as any)
const BestiaryKappaRoute = BestiaryKappaRouteImport.update({
  id: '/bestiary/kappa',
  path: '/bestiary/kappa',
  getParentRoute: () => rootRouteImport,
} as any)
const BestiaryKamadhenuRoute = BestiaryKamadhenuRouteImport.update({
  id: '/bestiary/kamadhenu',
  path: '/bestiary/kamadhenu',
  getParentRoute: () => rootRouteImport,
} as any)
const BestiaryJormungandrRoute = BestiaryJormungandrRouteImport.update({
  id: '/bestiary/jormungandr',
  path: '/bestiary/jormungandr',
  getParentRoute: () => rootRouteImport,
} as any)
const BestiaryHydraRoute = BestiaryHydraRouteImport.update({
  id: '/bestiary/hydra',
  path: '/bestiary/hydra',
  getParentRoute: () => rootRouteImport,
} as any)
const BestiaryHuginnMuninnRoute = BestiaryHuginnMuninnRouteImport.update({
  id: '/bestiary/huginn-muninn',
  path: '/bestiary/huginn-muninn',
  getParentRoute: () => rootRouteImport,
} as any)
const BestiaryGarudaRoute = BestiaryGarudaRouteImport.update({
  id: '/bestiary/garuda',
  path: '/bestiary/garuda',
  getParentRoute: () => rootRouteImport,
} as any)
const BestiaryGandharvaRoute = BestiaryGandharvaRouteImport.update({
  id: '/bestiary/gandharva',
  path: '/bestiary/gandharva',
  getParentRoute: () => rootRouteImport,
} as any)
const BestiaryGalluRoute = BestiaryGalluRouteImport.update({
  id: '/bestiary/gallu',
  path: '/bestiary/gallu',
  getParentRoute: () => rootRouteImport,
} as any)
const BestiaryFenrirRoute = BestiaryFenrirRouteImport.update({
  id: '/bestiary/fenrir',
  path: '/bestiary/fenrir',
  getParentRoute: () => rootRouteImport,
} as any)
const BestiaryFenghuangRoute = BestiaryFenghuangRouteImport.update({
  id: '/bestiary/fenghuang',
  path: '/bestiary/fenghuang',
  getParentRoute: () => rootRouteImport,
} as any)
const BestiaryEachUisgeRoute = BestiaryEachUisgeRouteImport.update({
  id: '/bestiary/each-uisge',
  path: '/bestiary/each-uisge',
  getParentRoute: () => rootRouteImport,
} as any)
const BestiaryDagdaStagRoute = BestiaryDagdaStagRouteImport.update({
  id: '/bestiary/dagda-stag',
  path: '/bestiary/dagda-stag',
  getParentRoute: () => rootRouteImport,
} as any)
const BestiaryCuSithRoute = BestiaryCuSithRouteImport.update({
  id: '/bestiary/cu-sith',
  path: '/bestiary/cu-sith',
  getParentRoute: () => rootRouteImport,
} as any)
const BestiaryChimeraRoute = BestiaryChimeraRouteImport.update({
  id: '/bestiary/chimera',
  path: '/bestiary/chimera',
  getParentRoute: () => rootRouteImport,
} as any)
const BestiaryCerberusRoute = BestiaryCerberusRouteImport.update({
  id: '/bestiary/cerberus',
  path: '/bestiary/cerberus',
  getParentRoute: () => rootRouteImport,
} as any)
const BestiaryBennuRoute = BestiaryBennuRouteImport.update({
  id: '/bestiary/bennu',
  path: '/bestiary/bennu',
  getParentRoute: () => rootRouteImport,
} as any)
const BestiaryBehemothRoute = BestiaryBehemothRouteImport.update({
  id: '/bestiary/behemoth',
  path: '/bestiary/behemoth',
  getParentRoute: () => rootRouteImport,
} as any)
const BestiaryBansheeRoute = BestiaryBansheeRouteImport.update({
  id: '/bestiary/banshee',
  path: '/bestiary/banshee',
  getParentRoute: () => rootRouteImport,
} as any)
const BestiaryBaiZeRoute = BestiaryBaiZeRouteImport.update({
  id: '/bestiary/bai-ze',
  path: '/bestiary/bai-ze',
  getParentRoute: () => rootRouteImport,
} as any)
const BestiaryApepRoute = BestiaryApepRouteImport.update({
  id: '/bestiary/apep',
  path: '/bestiary/apep',
  getParentRoute: () => rootRouteImport,
} as any)
const BestiaryAnzuRoute = BestiaryAnzuRouteImport.update({
  id: '/bestiary/anzu',
  path: '/bestiary/anzu',
  getParentRoute: () => rootRouteImport,
} as any)
const BestiaryAmmitRoute = BestiaryAmmitRouteImport.update({
  id: '/bestiary/ammit',
  path: '/bestiary/ammit',
  getParentRoute: () => rootRouteImport,
} as any)
const BestiaryAiravataRoute = BestiaryAiravataRouteImport.update({
  id: '/bestiary/airavata',
  path: '/bestiary/airavata',
  getParentRoute: () => rootRouteImport,
} as any)
const BestiaryIdRoute = BestiaryIdRouteImport.update({
  id: '/bestiary/$id',
  path: '/bestiary/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/forbidden': typeof ForbiddenRoute
  '/map': typeof MapRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/bestiary/$id': typeof BestiaryIdRoute
  '/bestiary/airavata': typeof BestiaryAiravataRoute
  '/bestiary/ammit': typeof BestiaryAmmitRoute
  '/bestiary/anzu': typeof BestiaryAnzuRoute
  '/bestiary/apep': typeof BestiaryApepRoute
  '/bestiary/bai-ze': typeof BestiaryBaiZeRoute
  '/bestiary/banshee': typeof BestiaryBansheeRoute
  '/bestiary/behemoth': typeof BestiaryBehemothRoute
  '/bestiary/bennu': typeof BestiaryBennuRoute
  '/bestiary/cerberus': typeof BestiaryCerberusRoute
  '/bestiary/chimera': typeof BestiaryChimeraRoute
  '/bestiary/cu-sith': typeof BestiaryCuSithRoute
  '/bestiary/dagda-stag': typeof BestiaryDagdaStagRoute
  '/bestiary/each-uisge': typeof BestiaryEachUisgeRoute
  '/bestiary/fenghuang': typeof BestiaryFenghuangRoute
  '/bestiary/fenrir': typeof BestiaryFenrirRoute
  '/bestiary/gallu': typeof BestiaryGalluRoute
  '/bestiary/gandharva': typeof BestiaryGandharvaRoute
  '/bestiary/garuda': typeof BestiaryGarudaRoute
  '/bestiary/huginn-muninn': typeof BestiaryHuginnMuninnRoute
  '/bestiary/hydra': typeof BestiaryHydraRoute
  '/bestiary/jormungandr': typeof BestiaryJormungandrRoute
  '/bestiary/kamadhenu': typeof BestiaryKamadhenuRoute
  '/bestiary/kappa': typeof BestiaryKappaRoute
  '/bestiary/khepri': typeof BestiaryKhepriRoute
  '/bestiary/kinnara': typeof BestiaryKinnaraRoute
  '/bestiary/kitsune': typeof BestiaryKitsuneRoute
  '/bestiary/lamassu': typeof BestiaryLamassuRoute
  '/bestiary/leviathan': typeof BestiaryLeviathanRoute
  '/bestiary/long': typeof BestiaryLongRoute
  '/bestiary/makara': typeof BestiaryMakaraRoute
  '/bestiary/minotaur': typeof BestiaryMinotaurRoute
  '/bestiary/mushussu': typeof BestiaryMushussuRoute
  '/bestiary/naga': typeof BestiaryNagaRoute
  '/bestiary/nidhogg': typeof BestiaryNidhoggRoute
  '/bestiary/orochi': typeof BestiaryOrochiRoute
  '/bestiary/ouroboros': typeof BestiaryOuroborosRoute
  '/bestiary/pegasus': typeof BestiaryPegasusRoute
  '/bestiary/pixiu': typeof BestiaryPixiuRoute
  '/bestiary/qilin': typeof BestiaryQilinRoute
  '/bestiary/ryu': typeof BestiaryRyuRoute
  '/bestiary/selkie': typeof BestiarySelkieRoute
  '/bestiary/sharabha': typeof BestiarySharabhaRoute
  '/bestiary/sleipnir': typeof BestiarySleipnirRoute
  '/bestiary/sphinx': typeof BestiarySphinxRoute
  '/bestiary/tengu': typeof BestiaryTenguRoute
  '/bestiary/tiamat': typeof BestiaryTiamatRoute
  '/bestiary/vali': typeof BestiaryValiRoute
  '/bestiary/vanara': typeof BestiaryVanaraRoute
  '/categories/$slug': typeof CategoriesSlugRoute
  '/mythology/$slug': typeof MythologySlugRoute
  '/bestiary/': typeof BestiaryIndexRoute
  '/mythology/': typeof MythologyIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/forbidden': typeof ForbiddenRoute
  '/map': typeof MapRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/bestiary/$id': typeof BestiaryIdRoute
  '/bestiary/airavata': typeof BestiaryAiravataRoute
  '/bestiary/ammit': typeof BestiaryAmmitRoute
  '/bestiary/anzu': typeof BestiaryAnzuRoute
  '/bestiary/apep': typeof BestiaryApepRoute
  '/bestiary/bai-ze': typeof BestiaryBaiZeRoute
  '/bestiary/banshee': typeof BestiaryBansheeRoute
  '/bestiary/behemoth': typeof BestiaryBehemothRoute
  '/bestiary/bennu': typeof BestiaryBennuRoute
  '/bestiary/cerberus': typeof BestiaryCerberusRoute
  '/bestiary/chimera': typeof BestiaryChimeraRoute
  '/bestiary/cu-sith': typeof BestiaryCuSithRoute
  '/bestiary/dagda-stag': typeof BestiaryDagdaStagRoute
  '/bestiary/each-uisge': typeof BestiaryEachUisgeRoute
  '/bestiary/fenghuang': typeof BestiaryFenghuangRoute
  '/bestiary/fenrir': typeof BestiaryFenrirRoute
  '/bestiary/gallu': typeof BestiaryGalluRoute
  '/bestiary/gandharva': typeof BestiaryGandharvaRoute
  '/bestiary/garuda': typeof BestiaryGarudaRoute
  '/bestiary/huginn-muninn': typeof BestiaryHuginnMuninnRoute
  '/bestiary/hydra': typeof BestiaryHydraRoute
  '/bestiary/jormungandr': typeof BestiaryJormungandrRoute
  '/bestiary/kamadhenu': typeof BestiaryKamadhenuRoute
  '/bestiary/kappa': typeof BestiaryKappaRoute
  '/bestiary/khepri': typeof BestiaryKhepriRoute
  '/bestiary/kinnara': typeof BestiaryKinnaraRoute
  '/bestiary/kitsune': typeof BestiaryKitsuneRoute
  '/bestiary/lamassu': typeof BestiaryLamassuRoute
  '/bestiary/leviathan': typeof BestiaryLeviathanRoute
  '/bestiary/long': typeof BestiaryLongRoute
  '/bestiary/makara': typeof BestiaryMakaraRoute
  '/bestiary/minotaur': typeof BestiaryMinotaurRoute
  '/bestiary/mushussu': typeof BestiaryMushussuRoute
  '/bestiary/naga': typeof BestiaryNagaRoute
  '/bestiary/nidhogg': typeof BestiaryNidhoggRoute
  '/bestiary/orochi': typeof BestiaryOrochiRoute
  '/bestiary/ouroboros': typeof BestiaryOuroborosRoute
  '/bestiary/pegasus': typeof BestiaryPegasusRoute
  '/bestiary/pixiu': typeof BestiaryPixiuRoute
  '/bestiary/qilin': typeof BestiaryQilinRoute
  '/bestiary/ryu': typeof BestiaryRyuRoute
  '/bestiary/selkie': typeof BestiarySelkieRoute
  '/bestiary/sharabha': typeof BestiarySharabhaRoute
  '/bestiary/sleipnir': typeof BestiarySleipnirRoute
  '/bestiary/sphinx': typeof BestiarySphinxRoute
  '/bestiary/tengu': typeof BestiaryTenguRoute
  '/bestiary/tiamat': typeof BestiaryTiamatRoute
  '/bestiary/vali': typeof BestiaryValiRoute
  '/bestiary/vanara': typeof BestiaryVanaraRoute
  '/categories/$slug': typeof CategoriesSlugRoute
  '/mythology/$slug': typeof MythologySlugRoute
  '/bestiary': typeof BestiaryIndexRoute
  '/mythology': typeof MythologyIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/forbidden': typeof ForbiddenRoute
  '/map': typeof MapRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/bestiary/$id': typeof BestiaryIdRoute
  '/bestiary/airavata': typeof BestiaryAiravataRoute
  '/bestiary/ammit': typeof BestiaryAmmitRoute
  '/bestiary/anzu': typeof BestiaryAnzuRoute
  '/bestiary/apep': typeof BestiaryApepRoute
  '/bestiary/bai-ze': typeof BestiaryBaiZeRoute
  '/bestiary/banshee': typeof BestiaryBansheeRoute
  '/bestiary/behemoth': typeof BestiaryBehemothRoute
  '/bestiary/bennu': typeof BestiaryBennuRoute
  '/bestiary/cerberus': typeof BestiaryCerberusRoute
  '/bestiary/chimera': typeof BestiaryChimeraRoute
  '/bestiary/cu-sith': typeof BestiaryCuSithRoute
  '/bestiary/dagda-stag': typeof BestiaryDagdaStagRoute
  '/bestiary/each-uisge': typeof BestiaryEachUisgeRoute
  '/bestiary/fenghuang': typeof BestiaryFenghuangRoute
  '/bestiary/fenrir': typeof BestiaryFenrirRoute
  '/bestiary/gallu': typeof BestiaryGalluRoute
  '/bestiary/gandharva': typeof BestiaryGandharvaRoute
  '/bestiary/garuda': typeof BestiaryGarudaRoute
  '/bestiary/huginn-muninn': typeof BestiaryHuginnMuninnRoute
  '/bestiary/hydra': typeof BestiaryHydraRoute
  '/bestiary/jormungandr': typeof BestiaryJormungandrRoute
  '/bestiary/kamadhenu': typeof BestiaryKamadhenuRoute
  '/bestiary/kappa': typeof BestiaryKappaRoute
  '/bestiary/khepri': typeof BestiaryKhepriRoute
  '/bestiary/kinnara': typeof BestiaryKinnaraRoute
  '/bestiary/kitsune': typeof BestiaryKitsuneRoute
  '/bestiary/lamassu': typeof BestiaryLamassuRoute
  '/bestiary/leviathan': typeof BestiaryLeviathanRoute
  '/bestiary/long': typeof BestiaryLongRoute
  '/bestiary/makara': typeof BestiaryMakaraRoute
  '/bestiary/minotaur': typeof BestiaryMinotaurRoute
  '/bestiary/mushussu': typeof BestiaryMushussuRoute
  '/bestiary/naga': typeof BestiaryNagaRoute
  '/bestiary/nidhogg': typeof BestiaryNidhoggRoute
  '/bestiary/orochi': typeof BestiaryOrochiRoute
  '/bestiary/ouroboros': typeof BestiaryOuroborosRoute
  '/bestiary/pegasus': typeof BestiaryPegasusRoute
  '/bestiary/pixiu': typeof BestiaryPixiuRoute
  '/bestiary/qilin': typeof BestiaryQilinRoute
  '/bestiary/ryu': typeof BestiaryRyuRoute
  '/bestiary/selkie': typeof BestiarySelkieRoute
  '/bestiary/sharabha': typeof BestiarySharabhaRoute
  '/bestiary/sleipnir': typeof BestiarySleipnirRoute
  '/bestiary/sphinx': typeof BestiarySphinxRoute
  '/bestiary/tengu': typeof BestiaryTenguRoute
  '/bestiary/tiamat': typeof BestiaryTiamatRoute
  '/bestiary/vali': typeof BestiaryValiRoute
  '/bestiary/vanara': typeof BestiaryVanaraRoute
  '/categories/$slug': typeof CategoriesSlugRoute
  '/mythology/$slug': typeof MythologySlugRoute
  '/bestiary/': typeof BestiaryIndexRoute
  '/mythology/': typeof MythologyIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/forbidden'
    | '/map'
    | '/sitemap.xml'
    | '/bestiary/$id'
    | '/bestiary/airavata'
    | '/bestiary/ammit'
    | '/bestiary/anzu'
    | '/bestiary/apep'
    | '/bestiary/bai-ze'
    | '/bestiary/banshee'
    | '/bestiary/behemoth'
    | '/bestiary/bennu'
    | '/bestiary/cerberus'
    | '/bestiary/chimera'
    | '/bestiary/cu-sith'
    | '/bestiary/dagda-stag'
    | '/bestiary/each-uisge'
    | '/bestiary/fenghuang'
    | '/bestiary/fenrir'
    | '/bestiary/gallu'
    | '/bestiary/gandharva'
    | '/bestiary/garuda'
    | '/bestiary/huginn-muninn'
    | '/bestiary/hydra'
    | '/bestiary/jormungandr'
    | '/bestiary/kamadhenu'
    | '/bestiary/kappa'
    | '/bestiary/khepri'
    | '/bestiary/kinnara'
    | '/bestiary/kitsune'
    | '/bestiary/lamassu'
    | '/bestiary/leviathan'
    | '/bestiary/long'
    | '/bestiary/makara'
    | '/bestiary/minotaur'
    | '/bestiary/mushussu'
    | '/bestiary/naga'
    | '/bestiary/nidhogg'
    | '/bestiary/orochi'
    | '/bestiary/ouroboros'
    | '/bestiary/pegasus'
    | '/bestiary/pixiu'
    | '/bestiary/qilin'
    | '/bestiary/ryu'
    | '/bestiary/selkie'
    | '/bestiary/sharabha'
    | '/bestiary/sleipnir'
    | '/bestiary/sphinx'
    | '/bestiary/tengu'
    | '/bestiary/tiamat'
    | '/bestiary/vali'
    | '/bestiary/vanara'
    | '/categories/$slug'
    | '/mythology/$slug'
    | '/bestiary/'
    | '/mythology/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/forbidden'
    | '/map'
    | '/sitemap.xml'
    | '/bestiary/$id'
    | '/bestiary/airavata'
    | '/bestiary/ammit'
    | '/bestiary/anzu'
    | '/bestiary/apep'
    | '/bestiary/bai-ze'
    | '/bestiary/banshee'
    | '/bestiary/behemoth'
    | '/bestiary/bennu'
    | '/bestiary/cerberus'
    | '/bestiary/chimera'
    | '/bestiary/cu-sith'
    | '/bestiary/dagda-stag'
    | '/bestiary/each-uisge'
    | '/bestiary/fenghuang'
    | '/bestiary/fenrir'
    | '/bestiary/gallu'
    | '/bestiary/gandharva'
    | '/bestiary/garuda'
    | '/bestiary/huginn-muninn'
    | '/bestiary/hydra'
    | '/bestiary/jormungandr'
    | '/bestiary/kamadhenu'
    | '/bestiary/kappa'
    | '/bestiary/khepri'
    | '/bestiary/kinnara'
    | '/bestiary/kitsune'
    | '/bestiary/lamassu'
    | '/bestiary/leviathan'
    | '/bestiary/long'
    | '/bestiary/makara'
    | '/bestiary/minotaur'
    | '/bestiary/mushussu'
    | '/bestiary/naga'
    | '/bestiary/nidhogg'
    | '/bestiary/orochi'
    | '/bestiary/ouroboros'
    | '/bestiary/pegasus'
    | '/bestiary/pixiu'
    | '/bestiary/qilin'
    | '/bestiary/ryu'
    | '/bestiary/selkie'
    | '/bestiary/sharabha'
    | '/bestiary/sleipnir'
    | '/bestiary/sphinx'
    | '/bestiary/tengu'
    | '/bestiary/tiamat'
    | '/bestiary/vali'
    | '/bestiary/vanara'
    | '/categories/$slug'
    | '/mythology/$slug'
    | '/bestiary'
    | '/mythology'
  id:
    | '__root__'
    | '/'
    | '/forbidden'
    | '/map'
    | '/sitemap.xml'
    | '/bestiary/$id'
    | '/bestiary/airavata'
    | '/bestiary/ammit'
    | '/bestiary/anzu'
    | '/bestiary/apep'
    | '/bestiary/bai-ze'
    | '/bestiary/banshee'
    | '/bestiary/behemoth'
    | '/bestiary/bennu'
    | '/bestiary/cerberus'
    | '/bestiary/chimera'
    | '/bestiary/cu-sith'
    | '/bestiary/dagda-stag'
    | '/bestiary/each-uisge'
    | '/bestiary/fenghuang'
    | '/bestiary/fenrir'
    | '/bestiary/gallu'
    | '/bestiary/gandharva'
    | '/bestiary/garuda'
    | '/bestiary/huginn-muninn'
    | '/bestiary/hydra'
    | '/bestiary/jormungandr'
    | '/bestiary/kamadhenu'
    | '/bestiary/kappa'
    | '/bestiary/khepri'
    | '/bestiary/kinnara'
    | '/bestiary/kitsune'
    | '/bestiary/lamassu'
    | '/bestiary/leviathan'
    | '/bestiary/long'
    | '/bestiary/makara'
    | '/bestiary/minotaur'
    | '/bestiary/mushussu'
    | '/bestiary/naga'
    | '/bestiary/nidhogg'
    | '/bestiary/orochi'
    | '/bestiary/ouroboros'
    | '/bestiary/pegasus'
    | '/bestiary/pixiu'
    | '/bestiary/qilin'
    | '/bestiary/ryu'
    | '/bestiary/selkie'
    | '/bestiary/sharabha'
    | '/bestiary/sleipnir'
    | '/bestiary/sphinx'
    | '/bestiary/tengu'
    | '/bestiary/tiamat'
    | '/bestiary/vali'
    | '/bestiary/vanara'
    | '/categories/$slug'
    | '/mythology/$slug'
    | '/bestiary/'
    | '/mythology/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ForbiddenRoute: typeof ForbiddenRoute
  MapRoute: typeof MapRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  BestiaryIdRoute: typeof BestiaryIdRoute
  BestiaryAiravataRoute: typeof BestiaryAiravataRoute
  BestiaryAmmitRoute: typeof BestiaryAmmitRoute
  BestiaryAnzuRoute: typeof BestiaryAnzuRoute
  BestiaryApepRoute: typeof BestiaryApepRoute
  BestiaryBaiZeRoute: typeof BestiaryBaiZeRoute
  BestiaryBansheeRoute: typeof BestiaryBansheeRoute
  BestiaryBehemothRoute: typeof BestiaryBehemothRoute
  BestiaryBennuRoute: typeof BestiaryBennuRoute
  BestiaryCerberusRoute: typeof BestiaryCerberusRoute
  BestiaryChimeraRoute: typeof BestiaryChimeraRoute
  BestiaryCuSithRoute: typeof BestiaryCuSithRoute
  BestiaryDagdaStagRoute: typeof BestiaryDagdaStagRoute
  BestiaryEachUisgeRoute: typeof BestiaryEachUisgeRoute
  BestiaryFenghuangRoute: typeof BestiaryFenghuangRoute
  BestiaryFenrirRoute: typeof BestiaryFenrirRoute
  BestiaryGalluRoute: typeof BestiaryGalluRoute
  BestiaryGandharvaRoute: typeof BestiaryGandharvaRoute
  BestiaryGarudaRoute: typeof BestiaryGarudaRoute
  BestiaryHuginnMuninnRoute: typeof BestiaryHuginnMuninnRoute
  BestiaryHydraRoute: typeof BestiaryHydraRoute
  BestiaryJormungandrRoute: typeof BestiaryJormungandrRoute
  BestiaryKamadhenuRoute: typeof BestiaryKamadhenuRoute
  BestiaryKappaRoute: typeof BestiaryKappaRoute
  BestiaryKhepriRoute: typeof BestiaryKhepriRoute
  BestiaryKinnaraRoute: typeof BestiaryKinnaraRoute
  BestiaryKitsuneRoute: typeof BestiaryKitsuneRoute
  BestiaryLamassuRoute: typeof BestiaryLamassuRoute
  BestiaryLeviathanRoute: typeof BestiaryLeviathanRoute
  BestiaryLongRoute: typeof BestiaryLongRoute
  BestiaryMakaraRoute: typeof BestiaryMakaraRoute
  BestiaryMinotaurRoute: typeof BestiaryMinotaurRoute
  BestiaryMushussuRoute: typeof BestiaryMushussuRoute
  BestiaryNagaRoute: typeof BestiaryNagaRoute
  BestiaryNidhoggRoute: typeof BestiaryNidhoggRoute
  BestiaryOrochiRoute: typeof BestiaryOrochiRoute
  BestiaryOuroborosRoute: typeof BestiaryOuroborosRoute
  BestiaryPegasusRoute: typeof BestiaryPegasusRoute
  BestiaryPixiuRoute: typeof BestiaryPixiuRoute
  BestiaryQilinRoute: typeof BestiaryQilinRoute
  BestiaryRyuRoute: typeof BestiaryRyuRoute
  BestiarySelkieRoute: typeof BestiarySelkieRoute
  BestiarySharabhaRoute: typeof BestiarySharabhaRoute
  BestiarySleipnirRoute: typeof BestiarySleipnirRoute
  BestiarySphinxRoute: typeof BestiarySphinxRoute
  BestiaryTenguRoute: typeof BestiaryTenguRoute
  BestiaryTiamatRoute: typeof BestiaryTiamatRoute
  BestiaryValiRoute: typeof BestiaryValiRoute
  BestiaryVanaraRoute: typeof BestiaryVanaraRoute
  CategoriesSlugRoute: typeof CategoriesSlugRoute
  MythologySlugRoute: typeof MythologySlugRoute
  BestiaryIndexRoute: typeof BestiaryIndexRoute
  MythologyIndexRoute: typeof MythologyIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/map': {
      id: '/map'
      path: '/map'
      fullPath: '/map'
      preLoaderRoute: typeof MapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forbidden': {
      id: '/forbidden'
      path: '/forbidden'
      fullPath: '/forbidden'
      preLoaderRoute: typeof ForbiddenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mythology/': {
      id: '/mythology/'
      path: '/mythology'
      fullPath: '/mythology/'
      preLoaderRoute: typeof MythologyIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bestiary/': {
      id: '/bestiary/'
      path: '/bestiary'
      fullPath: '/bestiary/'
      preLoaderRoute: typeof BestiaryIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mythology/$slug': {
      id: '/mythology/$slug'
      path: '/mythology/$slug'
      fullPath: '/mythology/$slug'
      preLoaderRoute: typeof MythologySlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/categories/$slug': {
      id: '/categories/$slug'
      path: '/categories/$slug'
      fullPath: '/categories/$slug'
      preLoaderRoute: typeof CategoriesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bestiary/vanara': {
      id: '/bestiary/vanara'
      path: '/bestiary/vanara'
      fullPath: '/bestiary/vanara'
      preLoaderRoute: typeof BestiaryVanaraRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bestiary/vali': {
      id: '/bestiary/vali'
      path: '/bestiary/vali'
      fullPath: '/bestiary/vali'
      preLoaderRoute: typeof BestiaryValiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bestiary/tiamat': {
      id: '/bestiary/tiamat'
      path: '/bestiary/tiamat'
      fullPath: '/bestiary/tiamat'
      preLoaderRoute: typeof BestiaryTiamatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bestiary/tengu': {
      id: '/bestiary/tengu'
      path: '/bestiary/tengu'
      fullPath: '/bestiary/tengu'
      preLoaderRoute: typeof BestiaryTenguRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bestiary/sphinx': {
      id: '/bestiary/sphinx'
      path: '/bestiary/sphinx'
      fullPath: '/bestiary/sphinx'
      preLoaderRoute: typeof BestiarySphinxRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bestiary/sleipnir': {
      id: '/bestiary/sleipnir'
      path: '/bestiary/sleipnir'
      fullPath: '/bestiary/sleipnir'
      preLoaderRoute: typeof BestiarySleipnirRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bestiary/sharabha': {
      id: '/bestiary/sharabha'
      path: '/bestiary/sharabha'
      fullPath: '/bestiary/sharabha'
      preLoaderRoute: typeof BestiarySharabhaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bestiary/selkie': {
      id: '/bestiary/selkie'
      path: '/bestiary/selkie'
      fullPath: '/bestiary/selkie'
      preLoaderRoute: typeof BestiarySelkieRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bestiary/ryu': {
      id: '/bestiary/ryu'
      path: '/bestiary/ryu'
      fullPath: '/bestiary/ryu'
      preLoaderRoute: typeof BestiaryRyuRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bestiary/qilin': {
      id: '/bestiary/qilin'
      path: '/bestiary/qilin'
      fullPath: '/bestiary/qilin'
      preLoaderRoute: typeof BestiaryQilinRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bestiary/pixiu': {
      id: '/bestiary/pixiu'
      path: '/bestiary/pixiu'
      fullPath: '/bestiary/pixiu'
      preLoaderRoute: typeof BestiaryPixiuRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bestiary/pegasus': {
      id: '/bestiary/pegasus'
      path: '/bestiary/pegasus'
      fullPath: '/bestiary/pegasus'
      preLoaderRoute: typeof BestiaryPegasusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bestiary/ouroboros': {
      id: '/bestiary/ouroboros'
      path: '/bestiary/ouroboros'
      fullPath: '/bestiary/ouroboros'
      preLoaderRoute: typeof BestiaryOuroborosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bestiary/orochi': {
      id: '/bestiary/orochi'
      path: '/bestiary/orochi'
      fullPath: '/bestiary/orochi'
      preLoaderRoute: typeof BestiaryOrochiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bestiary/nidhogg': {
      id: '/bestiary/nidhogg'
      path: '/bestiary/nidhogg'
      fullPath: '/bestiary/nidhogg'
      preLoaderRoute: typeof BestiaryNidhoggRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bestiary/naga': {
      id: '/bestiary/naga'
      path: '/bestiary/naga'
      fullPath: '/bestiary/naga'
      preLoaderRoute: typeof BestiaryNagaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bestiary/mushussu': {
      id: '/bestiary/mushussu'
      path: '/bestiary/mushussu'
      fullPath: '/bestiary/mushussu'
      preLoaderRoute: typeof BestiaryMushussuRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bestiary/minotaur': {
      id: '/bestiary/minotaur'
      path: '/bestiary/minotaur'
      fullPath: '/bestiary/minotaur'
      preLoaderRoute: typeof BestiaryMinotaurRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bestiary/makara': {
      id: '/bestiary/makara'
      path: '/bestiary/makara'
      fullPath: '/bestiary/makara'
      preLoaderRoute: typeof BestiaryMakaraRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bestiary/long': {
      id: '/bestiary/long'
      path: '/bestiary/long'
      fullPath: '/bestiary/long'
      preLoaderRoute: typeof BestiaryLongRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bestiary/leviathan': {
      id: '/bestiary/leviathan'
      path: '/bestiary/leviathan'
      fullPath: '/bestiary/leviathan'
      preLoaderRoute: typeof BestiaryLeviathanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bestiary/lamassu': {
      id: '/bestiary/lamassu'
      path: '/bestiary/lamassu'
      fullPath: '/bestiary/lamassu'
      preLoaderRoute: typeof BestiaryLamassuRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bestiary/kitsune': {
      id: '/bestiary/kitsune'
      path: '/bestiary/kitsune'
      fullPath: '/bestiary/kitsune'
      preLoaderRoute: typeof BestiaryKitsuneRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bestiary/kinnara': {
      id: '/bestiary/kinnara'
      path: '/bestiary/kinnara'
      fullPath: '/bestiary/kinnara'
      preLoaderRoute: typeof BestiaryKinnaraRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bestiary/khepri': {
      id: '/bestiary/khepri'
      path: '/bestiary/khepri'
      fullPath: '/bestiary/khepri'
      preLoaderRoute: typeof BestiaryKhepriRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bestiary/kappa': {
      id: '/bestiary/kappa'
      path: '/bestiary/kappa'
      fullPath: '/bestiary/kappa'
      preLoaderRoute: typeof BestiaryKappaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bestiary/kamadhenu': {
      id: '/bestiary/kamadhenu'
      path: '/bestiary/kamadhenu'
      fullPath: '/bestiary/kamadhenu'
      preLoaderRoute: typeof BestiaryKamadhenuRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bestiary/jormungandr': {
      id: '/bestiary/jormungandr'
      path: '/bestiary/jormungandr'
      fullPath: '/bestiary/jormungandr'
      preLoaderRoute: typeof BestiaryJormungandrRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bestiary/hydra': {
      id: '/bestiary/hydra'
      path: '/bestiary/hydra'
      fullPath: '/bestiary/hydra'
      preLoaderRoute: typeof BestiaryHydraRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bestiary/huginn-muninn': {
      id: '/bestiary/huginn-muninn'
      path: '/bestiary/huginn-muninn'
      fullPath: '/bestiary/huginn-muninn'
      preLoaderRoute: typeof BestiaryHuginnMuninnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bestiary/garuda': {
      id: '/bestiary/garuda'
      path: '/bestiary/garuda'
      fullPath: '/bestiary/garuda'
      preLoaderRoute: typeof BestiaryGarudaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bestiary/gandharva': {
      id: '/bestiary/gandharva'
      path: '/bestiary/gandharva'
      fullPath: '/bestiary/gandharva'
      preLoaderRoute: typeof BestiaryGandharvaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bestiary/gallu': {
      id: '/bestiary/gallu'
      path: '/bestiary/gallu'
      fullPath: '/bestiary/gallu'
      preLoaderRoute: typeof BestiaryGalluRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bestiary/fenrir': {
      id: '/bestiary/fenrir'
      path: '/bestiary/fenrir'
      fullPath: '/bestiary/fenrir'
      preLoaderRoute: typeof BestiaryFenrirRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bestiary/fenghuang': {
      id: '/bestiary/fenghuang'
      path: '/bestiary/fenghuang'
      fullPath: '/bestiary/fenghuang'
      preLoaderRoute: typeof BestiaryFenghuangRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bestiary/each-uisge': {
      id: '/bestiary/each-uisge'
      path: '/bestiary/each-uisge'
      fullPath: '/bestiary/each-uisge'
      preLoaderRoute: typeof BestiaryEachUisgeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bestiary/dagda-stag': {
      id: '/bestiary/dagda-stag'
      path: '/bestiary/dagda-stag'
      fullPath: '/bestiary/dagda-stag'
      preLoaderRoute: typeof BestiaryDagdaStagRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bestiary/cu-sith': {
      id: '/bestiary/cu-sith'
      path: '/bestiary/cu-sith'
      fullPath: '/bestiary/cu-sith'
      preLoaderRoute: typeof BestiaryCuSithRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bestiary/chimera': {
      id: '/bestiary/chimera'
      path: '/bestiary/chimera'
      fullPath: '/bestiary/chimera'
      preLoaderRoute: typeof BestiaryChimeraRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bestiary/cerberus': {
      id: '/bestiary/cerberus'
      path: '/bestiary/cerberus'
      fullPath: '/bestiary/cerberus'
      preLoaderRoute: typeof BestiaryCerberusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bestiary/bennu': {
      id: '/bestiary/bennu'
      path: '/bestiary/bennu'
      fullPath: '/bestiary/bennu'
      preLoaderRoute: typeof BestiaryBennuRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bestiary/behemoth': {
      id: '/bestiary/behemoth'
      path: '/bestiary/behemoth'
      fullPath: '/bestiary/behemoth'
      preLoaderRoute: typeof BestiaryBehemothRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bestiary/banshee': {
      id: '/bestiary/banshee'
      path: '/bestiary/banshee'
      fullPath: '/bestiary/banshee'
      preLoaderRoute: typeof BestiaryBansheeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bestiary/bai-ze': {
      id: '/bestiary/bai-ze'
      path: '/bestiary/bai-ze'
      fullPath: '/bestiary/bai-ze'
      preLoaderRoute: typeof BestiaryBaiZeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bestiary/apep': {
      id: '/bestiary/apep'
      path: '/bestiary/apep'
      fullPath: '/bestiary/apep'
      preLoaderRoute: typeof BestiaryApepRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bestiary/anzu': {
      id: '/bestiary/anzu'
      path: '/bestiary/anzu'
      fullPath: '/bestiary/anzu'
      preLoaderRoute: typeof BestiaryAnzuRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bestiary/ammit': {
      id: '/bestiary/ammit'
      path: '/bestiary/ammit'
      fullPath: '/bestiary/ammit'
      preLoaderRoute: typeof BestiaryAmmitRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bestiary/airavata': {
      id: '/bestiary/airavata'
      path: '/bestiary/airavata'
      fullPath: '/bestiary/airavata'
      preLoaderRoute: typeof BestiaryAiravataRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bestiary/$id': {
      id: '/bestiary/$id'
      path: '/bestiary/$id'
      fullPath: '/bestiary/$id'
      preLoaderRoute: typeof BestiaryIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ForbiddenRoute: ForbiddenRoute,
  MapRoute: MapRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  BestiaryIdRoute: BestiaryIdRoute,
  BestiaryAiravataRoute: BestiaryAiravataRoute,
  BestiaryAmmitRoute: BestiaryAmmitRoute,
  BestiaryAnzuRoute: BestiaryAnzuRoute,
  BestiaryApepRoute: BestiaryApepRoute,
  BestiaryBaiZeRoute: BestiaryBaiZeRoute,
  BestiaryBansheeRoute: BestiaryBansheeRoute,
  BestiaryBehemothRoute: BestiaryBehemothRoute,
  BestiaryBennuRoute: BestiaryBennuRoute,
  BestiaryCerberusRoute: BestiaryCerberusRoute,
  BestiaryChimeraRoute: BestiaryChimeraRoute,
  BestiaryCuSithRoute: BestiaryCuSithRoute,
  BestiaryDagdaStagRoute: BestiaryDagdaStagRoute,
  BestiaryEachUisgeRoute: BestiaryEachUisgeRoute,
  BestiaryFenghuangRoute: BestiaryFenghuangRoute,
  BestiaryFenrirRoute: BestiaryFenrirRoute,
  BestiaryGalluRoute: BestiaryGalluRoute,
  BestiaryGandharvaRoute: BestiaryGandharvaRoute,
  BestiaryGarudaRoute: BestiaryGarudaRoute,
  BestiaryHuginnMuninnRoute: BestiaryHuginnMuninnRoute,
  BestiaryHydraRoute: BestiaryHydraRoute,
  BestiaryJormungandrRoute: BestiaryJormungandrRoute,
  BestiaryKamadhenuRoute: BestiaryKamadhenuRoute,
  BestiaryKappaRoute: BestiaryKappaRoute,
  BestiaryKhepriRoute: BestiaryKhepriRoute,
  BestiaryKinnaraRoute: BestiaryKinnaraRoute,
  BestiaryKitsuneRoute: BestiaryKitsuneRoute,
  BestiaryLamassuRoute: BestiaryLamassuRoute,
  BestiaryLeviathanRoute: BestiaryLeviathanRoute,
  BestiaryLongRoute: BestiaryLongRoute,
  BestiaryMakaraRoute: BestiaryMakaraRoute,
  BestiaryMinotaurRoute: BestiaryMinotaurRoute,
  BestiaryMushussuRoute: BestiaryMushussuRoute,
  BestiaryNagaRoute: BestiaryNagaRoute,
  BestiaryNidhoggRoute: BestiaryNidhoggRoute,
  BestiaryOrochiRoute: BestiaryOrochiRoute,
  BestiaryOuroborosRoute: BestiaryOuroborosRoute,
  BestiaryPegasusRoute: BestiaryPegasusRoute,
  BestiaryPixiuRoute: BestiaryPixiuRoute,
  BestiaryQilinRoute: BestiaryQilinRoute,
  BestiaryRyuRoute: BestiaryRyuRoute,
  BestiarySelkieRoute: BestiarySelkieRoute,
  BestiarySharabhaRoute: BestiarySharabhaRoute,
  BestiarySleipnirRoute: BestiarySleipnirRoute,
  BestiarySphinxRoute: BestiarySphinxRoute,
  BestiaryTenguRoute: BestiaryTenguRoute,
  BestiaryTiamatRoute: BestiaryTiamatRoute,
  BestiaryValiRoute: BestiaryValiRoute,
  BestiaryVanaraRoute: BestiaryVanaraRoute,
  CategoriesSlugRoute: CategoriesSlugRoute,
  MythologySlugRoute: MythologySlugRoute,
  BestiaryIndexRoute: BestiaryIndexRoute,
  MythologyIndexRoute: MythologyIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
